import Head from "next/head";
import { useSelector } from "react-redux";
import TopBar from "../components/TopBar";
import { useRefreshToken } from "../helpers/useRefreshToken";

export default function Home() {
  // call refresh endpoint
  const { loading } = useRefreshToken();

  if (loading) {
    return (
      <div className="flex h-screen items-center justify-center">
        <span className="text-xl font-semibold tracking-widest animate-pulse">
          Loading....
        </span>
      </div>
    );
  }
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-screen bg-white">
        <TopBar />
      </main>
    </div>
  );
}
