import Head from "next/head";
import TopBar from "../components/TopBar";
import SearchSection from "../components/SearchSection";
import { useRefreshToken } from "../helpers/useRefreshToken";
import { getAllJobs } from "../services/job_services";
import Filters from "../components/Filters";
import RecommendedJobs from "../components/RecommendedJobs";
import { useRouter } from "next/router";

function Jobs({ jobs }) {
  // call refresh endpoint
  const { loading } = useRefreshToken();
  const router = useRouter();

  if (loading) {
    return (
      <div className="flex h-screen items-center justify-center">
        <span className="animate-pulse text-xl font-semibold tracking-widest">
          Loading....
        </span>
      </div>
    );
  }
  return (
    <div>
      <Head>
        <title>Home - Jobspot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-100 ">
        <TopBar />
        <SearchSection />

        <div className="flex px-6 pt-80 md:px-16 md:pt-44">
          {/* filters */}
          <Filters jobs={jobs} />
          <div className="flex">All jobs</div>
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { data } = await getAllJobs();

  return {
    props: {
      jobs: data.jobs,
    },
  };
}

export default Jobs;
