import Head from "next/head";
import TopBar from "../../components/TopBar";
import SearchSection from "../../components/SearchSection";
import { getAllJobs } from "../../services/job_services";
import Filters from "../../components/Filters";
import RecommendedJobs from "../../components/RecommendedJobs";

function Jobs({ jobs }) {
  return (
    <div>
      <Head>
        <title>Jobs - Jobspot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-50 ">
        <TopBar />
        <SearchSection />

        <div className="flex h-screen px-6 pt-96 md:px-16 md:pt-44">
          {/* filters */}
          <Filters jobs={jobs} isAllJobs={true} />
          <RecommendedJobs isAllJobs={true} />
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { data } = await getAllJobs();

  return {
    props: {
      jobs: data.jobs,
    },
  };
}

export default Jobs;
